### PR TITLE
Update README.md to include gcc-c+ dependency

### PR DESCRIPTION
**Pull request by michaelcoburn**
adding in note to install gcc-c+ package (needed on CentOS 7)

### CODE REVIEW

**Comment by michaelcoburn** [comment]
Solves this:
`[root@ps1 pquery]# cmake . -DPERCONASERVER=ON
-- The CXX compiler identification is unknown
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
-- * BASEDIR is set, looking for Percona Server in /usr
-- Configuring incomplete, errors occurred!`

**Comment by michaelcoburn** [comment]
Now:
`[root@ps1 pquery]# cmake . -DPERCONASERVER=ON
-- The CXX compiler identification is GNU 4.8.3
-- Check for working CXX compiler: /usr/bin/gcc
-- Check for working CXX compiler: /usr/bin/gcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- * BASEDIR is set, looking for Percona Server in /usr
-- Configuring done
-- Generating done
-- Build files have been written to: /root/pquery`

**Comment by abychko** [comment]
Michael, it's OK, but:
1) you have a typo in your PR - it should be gcc-c++, not gcc-c+ 
2) it's applicable for Centos/RedHat only, for example Ubuntu has g++ package, not gcc-c++
that was a reason to require abstract GCC package with C++11 support

**Comment by abychko** [comment]
fixed by separate commit

**Pull request closed without merging**
